[package]
name = "wiki-server"
version = "0.1.0"
authors = ["Sander Dijkhuis <sander.dijkhuis@cleverbase.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.8.0"
regex = { version = "1.4.1" }