name: Publish wiki

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -L https://github.com/sander/hashtagwiki/releases/download/v0.1.0/hashtagwiki-linux -o hashtagwiki
      - run: chmod +x hashtagwiki
      - run: ./hashtagwiki publish
      - uses: actions/upload-artifact@v1
        with:
          name: wiki
          path: out/
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wiki
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Deploy
        run: aws s3 sync --delete --acl public-read . s3://hashtagwiki.sanderdijkhuis.nl
